---
title: "Презентация. Лабораторная работа №1"
author: "Пустобавев Леонид | НММбд-03-2024 | 1132246818"
date: "`r Sys.Date()`"
output:
  beamer_presentation:
    toc: true
    slide_level: 2
  ioslides_presentation:
    widescreen: true
    smaller: true
---

Ход работы
Установка Linux на VirtualBox
Настройка каталога для виртуальных машин
Я запустил терминал и перешёл в каталог /var/tmp командой cd /var/tmp.

Создал каталог с именем, совпадающим с моим логином: mkdir /var/tmp/$(id -un).

Проверил и изменил в настройках VirtualBox путь для каталога виртуальных машин на /var/tmp/мой_логин.

Настройка хост-клавиши
Поскольку правая клавиша Ctrl в дисплейном классе используется для переключения языка, я изменил хост-клавишу VirtualBox на другую, например, клавишу Menu, через настройки графического интерфейса или командой:
VBoxManage setextradata global GUI/Input/HostKeyCombination 65383

Создание виртуальной машины
Я создал новую виртуальную машину с именем мой_логин_os-intro и типом ОС Fedora (64-bit).

Выделил для неё 2048 МБ оперативной памяти.

Создал динамический виртуальный жесткий диск размером 80 ГБ (VDI формат).

Подключил загрузочный ISO-образ Fedora Sway к виртуальному приводу оптических дисков.

В настройках видеоадаптера выбрал контроллер VMSVGA, включил 3D-ускорение и выделил 128 МБ видеопамяти.

Включил общий буфер обмена и функцию перетаскивания в двустороннем режиме.

Включил поддержку UEFI.

Установка операционной системы
Я запустил виртуальную машину и начал установку с LiveCD.

В запущенном Live-окружении нажал Win+Enter для запуска терминала и выполнил команду liveinst для начала установки.

В процессе установки я:

Выбрал язык интерфейса и раскладки клавиатуры.

В качестве места установки указал созданный ранее виртуальный диск.

Задал имя хоста, совпадающее с моим логином.

Создал пользователя с моим логином и задал пароль.

Установил пароль для root.

После завершения установки перезагрузил виртуальную машину и отключил установочный ISO-образ.

Послеустановочная настройка
Установка дополнений гостевой ОС
Я вошёл в систему под своей учётной записью.

Запустил терминал (Win+Enter), активировал tmux и перешёл в режим суперпользователя: sudo -i.

Установил необходимые пакеты для сборки модулей ядра: dnf -y group install development-tools и dnf -y install dkms.

Через меню VirtualBox подключил образ диска с дополнениями гостевой ОС.

Вмонтировал диск командой mount /dev/sr0 /media и запустил скрипт установки: /media/VBoxLinuxAdditions.run.

Перезагрузил виртуальную машину командой reboot.

Настройка общего доступа к папкам
Добавил своего пользователя в группу vboxsf: sudo gpasswd -a мой_логин vboxsf.

На хостовой машине создал общую папку work и подключил её к виртуальной машине через настройки Shared Folders в VirtualBox.

Ещё раз перезагрузил виртуальную машину для применения изменений.

Обновление системы и установка базового ПО
Обновил все пакеты в системе: sudo dnf -y update.

Установил программы для удобства работы в консоли: sudo dnf -y install tmux mc.

Настройка раскладки клавиатуры
Для удобного переключения между русской и английской раскладками я создал и настроил конфигурационный файл ~/.config/sway/config.d/95-system-keyboard-config.conf, добавив в него строку:
exec_always /usr/libexec/sway-systemd/locale1-xkb-config --oneshot

А также отредактировал системный конфиг /etc/X11/xorg.conf.d/00-keyboard.conf, указав нужные опции XkbLayout, XkbVariant и XkbOptions.

Установка ПО для документации
Установил pandoc и TeXlive для генерации документов: sudo dnf -y install pandoc texlive-scheme-full.

Выводы
В ходе данной лабораторной работы я приобрел первоначальные практические навыки установки операционной системы Linux (дистрибутив Fedora) на виртуальную машину VirtualBox. Я научился настраивать параметры виртуальной машины, такие как объем памяти, тип видеоадаптера и общие ресурсы. После установки ОС я выполнил базовую настройку системы: установил дополнения для VirtualBox, настроил общие папки для обмена данными с хост-системой, обновил системные пакеты и установил необходимое программное обеспечение для дальнейшей работы. В результате была получена готовая к использованию виртуальная среда для выполнения последующих лабораторных работ.


