---
title: "Отчёт по лабораторной работе №1"
author: "Пустобаев Леонид"
group: "НММбд-03-2024"
student_id: "1132246818"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    number_sections: yes
  html_document:
    toc: yes
    number_sections: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "screenshots/")
screenshot_dir <- here::here("lab`01`", "screenshots")
```

Цель работы
Целью данной работы является изучение идеологии и применения средств контроля версий, а также освоение практических навыков работы с системой git.

Ход работы
Базовая настройка git
Я начал с настройки основных параметров git, указав свое имя и email. Выполнил следующие команды:

git config --global user.name "Иванов Иван"
git config --global user.email "ivanov@example.com"
git config --global core.quotepath false
git config --global init.defaultBranch master
git config --global core.autocrlf input
git config --global core.safecrlf warn

Создание SSH-ключей
Сгенерировал SSH-ключи для безопасного подключения к удаленным репозиториям. Выполнил команды:

ssh-keygen -t rsa -b 4096
ssh-keygen -t ed25519

Создание PGP-ключей
Создал PGP-ключ для подписи коммитов с помощью команды:

gpg --full-generate-key

Выбрал тип RSA and RSA с размером 4096 бит и указал свои данные при запросе.

Настройка GitHub
Зарегистрировался на GitHub и добавил SSH-ключ в настройках аккаунта. Для этого скопировал публичный ключ командой:

cat ~/.ssh/id_ed25519.pub

и добавил его в разделе SSH and GPG keys настроек GitHub.

Экспортировал PGP-ключ и также добавил его в настройках GitHub с помощью команды:

gpg --armor --export и указал отпечаток ключа

Настройка автоматической подписи коммитов
Настроил git для автоматической подписи коммитов командами:

git config --global user.signingkey указал отпечаток PGP ключа
git config --global commit.gpgsign true

Создание рабочего пространства
Создал каталог для лабораторных работ и инициализировал git-репозиторий:

mkdir -p ~/work/study/2023-2024/os-intro
cd ~/work/study/2023-2024/os-intro
git init

Создал тестовый файл и сделал первый коммит:

echo "Начало работы над лабораторными" > README.md
git add README.md
git commit -S -m "feat: initial commit"

Работа с удаленным репозиторием
Связал локальный репозиторий с удаленным на GitHub:

git remote add origin указал ссылку на репозиторий
git push -u origin master

Выводы
В ходе выполнения лабораторной работы я освоил основные принципы работы с системой контроля версий Git. Я научился настраивать рабочее окружение, создавать и настраивать SSH и PGP ключи для безопасной работы, а также подписывать коммиты для обеспечения их подлинности. Были получены практические навыки работы с базовыми командами git: создание репозитория, добавление файлов, создание коммитов и синхронизация с удаленным репозиторием на GitHub. Все цели работы были успешно достигнуты, и теперь я готов использовать git для последующих лабораторных работ и проектов.


