---
title: "Отчёт по лабораторной работе №3"
author: "Пустобаев Леонид"
group: "НММбд-03-2024"
student_id: "1132246818"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    number_sections: yes
  html_document:
    toc: yes
    number_sections: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "screenshots/")
screenshot_dir <- here::here("lab`03`", "screenshots")
```

Цель работы
Целью данной работы является освоение языка разметки Markdown для оформления отчетов. В ходе работы я планировал изучить базовый синтаксис Markdown, научиться создавать структурированные документы и освоить преобразование Markdown-файлов в другие форматы.

Ход работы
Изучение базового синтаксиса Markdown
Я начал с изучения основных элементов языка разметки Markdown. Для создания заголовков я использовал знаки решетки разного уровня, начиная от одного символа для заголовков первого уровня и до шести для более мелких заголовков.

Для форматирования текста я применял различные комбинации звездочек: двойные для полужирного начертания, одинарные для курсива и тройные для комбинированного форматирования.

Я создал блок цитирования с помощью символа "больше" и убедился, что цитата правильно форматируется с сохранением переносов строк.

Работая со списками, я создал как маркированные списки с использованием дефисов, так и нумерованные списки с цифрами. Я также освоил создание вложенных списков, добавляя отступы для элементов дочернего списка.

Для вставки ссылок я использовал синтаксис с квадратными и круглыми скобками, а для выделения блоков кода применял тройные апострофы с указанием языка программирования.

Работа с математическими формулами
Я изучил вставку математических формул в текст. Для верхних и нижних индексов я использовал тильду и каретку соответственно. Для внутритекстовых формул я применял синтаксис LaTeX с долларовыми знаками, а для выносных формул с возможностью создания ссылок использовал двойные доллары с идентификаторами.

Установка и настройка Pandoc
Я установил Pandoc для преобразования Markdown-файлов в другие форматы. После установки я проверил работу утилиты, преобразовав тестовый файл в форматы PDF и DOCX, чтобы убедиться в корректности работы инструмента.

Создание комплексного отчета
Я создал полноценный отчет по лабораторной работе, включающий все необходимые структурные элементы: титульный лист, введение с целью и задачами работы, основную часть с описанием хода работы, заключение с выводами и список использованных источников. Для каждого раздела я использовал соответствующее оформление заголовков и обеспечил логическую структуру документа.

Преобразование в различные форматы
Я использовал Pandoc для конвертации готового отчета в различные форматы: PDF, DOCX и HTML. Для корректной обработки перекрестных ссылок я использовал фильтр pandoc-crossref. После преобразования я проверил результат во всех форматах и убедился в сохранении структуры и форматирования документа.

Выводы
В ходе выполнения лабораторной работы я успешно освоил язык разметки Markdown и научился создавать структурированные документы. Я изучил основные элементы синтаксиса, включая заголовки, форматирование текста, списки, таблицы и математические формулы. Я освоил работу с утилитой Pandoc для преобразования документов в различные форматы. Приобретенные навыки позволяют мне эффективно оформлять техническую документацию и отчетные материалы с использованием легковесного языка разметки Markdown, что значительно упрощает процесс создания и поддержки документации.